[package]
name = "az-agent-frontend"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
topcoat = { version = "=0.6.2", default-features = false, features = ["view"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow.workspace = true
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
serde.workspace = true
serde_json.workspace = true
